= Perl 6 入门
Naoum Hankache <naoum@hankache.com>; Romuald Nuguet <kolikov@free.fr>
:description: Perl 6 入门教程
:keywords: perl6, perl 6, introduction, perl6intro, perl 6 introduction, Introduction à Perl 6, perl 6 入门, perl 6 教程
:Revision: 1.0
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: perl6
:pygments-linenums-mode: table
:toc: left
:toc-title: 目录
:doctype: book
:lang: zh

本文档意在给予那些 Perl 6的新人一个Perl 6 语言的快速概述。

本文档中的一些章节会引用 https://docs.perl6.org[Perl 6文档]的部分内容（更加完整、准确），
如果你需要知晓特定主题的详细信息，我推荐你阅读它们。

在本文档中，你将发现例子是讨论最多的话题，为了更好的理解它们，最好花时间重现这些例子。

.许可
这份文档使用 Creative Commons Attribution-ShareAlike 4.0 International 许可发布。
要查看许可的副本，请访问

* http://creativecommons.org/licenses/by-sa/4.0/。

.贡献
对本文档的完善提供帮助:

* http://github.com/hankache/perl6intro。

.反馈
欢迎您的反馈:
naoum@hankache.com
blackcatoverwall@gmail.com

如果你喜欢本文档，请_Star_这个仓库：
https://github.com/hankache/perl6intro[Github].

.译文
* Bulgarian: http://bg.perl6intro.com
* Dutch: http://nl.perl6intro.com
* French: http://fr.perl6intro.com
* German: http://de.perl6intro.com
* Japanese: http://ja.perl6intro.com
* Portuguese: http://pt.perl6intro.com
* Spanish: http://es.perl6intro.com
* Chinese - NYC: http://zh.perl6intro.com

:sectnums:
== 入门
=== 什么是 Perl 6
Perl 6 是一个高阶的，通用的，渐进类型（gradually typed）语言。
Perl 6 支持过程式、面向对象、函数式多中编程范式。

.Perl 6 座右铭:
* TMTOWTDI (来自 Tim Toady): 条条大路通罗马（There is more than one way to do it）.
* 简单的事情应该保持简单，困难的事情应该变的简单，以及不可能的事情应该变的困难（Easy
things should stay easy, hard things should get easier, and impossible things should get hard）。

=== 术语
* *Perl 6*: 含有一个测试套件的语言规范，实现并通过了测试套件的语言即认为是 Perl 6语言的实现。
* *Rakudo*: Perl 6的一个编译器。
* *Rakudobrew*: Rakudo 的安装管理器。
* *Panda*: 是一个 Perl 6的模块安装器。
* *Rakudo Star*: 对 Rakudo、Panda、Perl 6模块的集合以及文档进行了打包。

=== 安装 Perl 6
.Linux
. 安装 Rakudobrew: https://github.com/tadzik/rakudobrew

. 安装 Rakudo: 在终端输入以下命令 `rakudobrew build moar`

. 安装 Panda: 在终端输入以下命令 `rakudobrew build panda`

. 安装 Task::Star一个包含在Rakudo Star中的模块的超级包: 在终端输入以下命令 `panda install Task::Star`

更多其它选项, 请访问 http://rakudo.org/how-to-get-rakudo/#Installing-Rakudo-Star-Linux

.OSX
下面4中选项是可用的:

* 使用和 Linux 一样的安装步骤
* 使用 homebrew 安装: `brew install rakudo-star`
* 使用 MacPorts 安装: `sudo port install rakudo`
* 下载最新的安装器 (以 .dmg 后缀结尾): http://rakudo.org/downloads/star/

.Windows
. 下载最新的安装器 (以 .msi 后缀结尾): http://rakudo.org/downloads/star/ +
如果你的系统是`32`位的，请选择`x86`版本，如果是`64`位，下载`x86-64`的版本。
. 在完成安装之后确保`C:\rakudo\bin`已经添加到环境变量。

.Docker
. 获取官方 Docker 镜像 `docker pull rakudo-star`
. 使用下载的镜像启动一个容器 `docker run -it rakudo-star`

=== 运行 Perl 6代码

你可以使用 REPL（即读取-求值-打印 循环（Read-Eval-Print Loop））方式运行 Perl 6的代码。
方法就是，打开一个终端，在窗口输入`perl6`，然后回车，这时候会出现一个提示符'>'。接下来，
输入一行代码并且按下回车，REPL 将会打印出代码的结果。你还可以输入更多的代码或者输入`exit`
并按下回车键离开`REPL`。

或者，你可以将代码写入文件，保存，并且运行它，这里推荐 Perl 6的脚本使用`.pl6`扩展名。要
运行这个文件你只需在终端输入`perl6 filename.pl6`，然后按下回车。但是不像 REPL，这种方式
不会自动的打印每一行的结果：代码中必须包含形如`say`一样的语句来打印输出。

REPL 通常用来尝试一小段代码，这通常是单行代码（通常所说的 one-liner）。对于一行以上的
程序建立将代码存储在文件中，然后运行它们。

你还可以通过在命令行输入`perl6 -e '这里是你的代码'`并且按下回车来运行你的单行代码。

[TIP]
--
Rakudo Star 捆绑了一个行编辑器来帮助你更好的使用 REPL。

如果你安装了普通的 Rakudo 而不是 Rakudo Star，你可能没有开启行编译器功能（使用上下键
在历史命令移动，左右键编辑输入，TAB完成）。运行下面的命令来获取这个功能：

* 在 Windows、Linux、OSX上，可以使用 `panda install Linenoise`
* 如果是 Linux 系统，可能比较喜欢 _ReadLine_ 库 `panda install ReadLine`
--

=== 编辑器
因为大部分时间我们将会在文件里编写并且保存我们的 Perl 6程序，我们应该需要一个像样的可以
识别 Perl 6语法的文本编辑器。

我个人使用和推荐的是 https://atom.io/[Atom]。它是一个现代的文本编辑器，自带 Perl 6语法
高亮，即装即用。 https://atom.io/packages/language-perl6fe[Perl6-fe] 是另一个支持语法
高亮的 Atom插件，继承自原始插件并且修复了许多bug，还有额外的功能。

其他在社区的一些人还会使用 http://www.vim.org/[Vim]， https://www.gnu.org/software/emacs/[Emacs]
或者 http://padre.perlide.org/[Padre]。

最近版本的 Vim 语法高亮已经是开箱即用了，Emacs 还有 Padre 还需要安装额外的插件。

=== Hello World!
按照惯例，我们先从`hello world`程序开始

[source, perl6]
say 'hello world';

还可以这么写：

[source, perl6]
'hello world'.say;

=== 语法概述
Perl 6 是 *形式自由* 的：你可以（大多数情况下）任意数量的空格。

通常情况下， *陈述* 要成为语句，它们需要以分号尾：
`say "Hello" if True;`

*表达式* 是有返回值的特殊语句 ：
`1 + 2` 将会返回 `3`

表达式由 *项* 以及 *操作符* 组成。

*项* 指的是：

* *变量*：可以被操作以及改变的值。

* *字面量*：常量值比如数字或者字符串。

*操作符* 可以分为好几种：

|===

| *种类* | *注释* | *样例*

| 前缀 | 在项之前 | `+1`

| 中缀 | 在项之间 | `1 + 2`

| 后缀 | 在项之后 | `$x++`

| 环缀 | 环绕项   | `(1)`

| 后环缀 | 在项之后又环绕另一项 | `@x[1]`

|===

==== 标识符
标识符是你在定义项的时候给予它们的名字。

.规则:
* 必须以英文字母或者下划线打头

* 可以包含数字（除了首字符）

* 可以包含破折号或者撇号（除了首尾字符），只要在每个破折号或者撇号右侧紧跟着一个英文字母。

|===

| *合法* | *不合法*

| `var1` | `1var`

| `var-one` | `var-1`

| `var'one` | `var'1`

| `var1_` | `var1'`

| `_var` | `-var`

|===

.命名约定：
* 驼峰式： `variableNo1`

* 烤串式： `variable-no1`

* 蛇式：   `variable_no1`

你可以按照自己的喜好自由的对标识符命名，但采用一致的命名约定是一个好习惯。

使用有意义的名称将会方便你的（和其他人）编程工作。

* `var1 = var2 * var3` 语法上是正确的但是它意图并不明显。
* `monthly-salary = daily-rate * working-days` 像这样命名是一个好的方法

==== 注释
注释是一段被编译器忽略用来做注记的文本。

注释分为三类：

* 单行注释：
+
[source, perl6]
# 这是一个单行注释

* 内嵌注释：
+
[source, perl6]
say #`(这是内嵌注释) "Hello World."

* 多行注释
+
[source, perl6]
------------------------
=begin comment
这是多行注释
注释1
注释2
=end comment
------------------------

==== 引用
字符串双引号或者单引号来定界。

下列情况下使用双引号：

* 如果你的字符串含有一个撇号。

* 如果你的字符串包含一个需要内插的变量。

[source, perl6]
------------------------
say 'Hello World';      # Hello World
say "Hello World";      # Hello World
say "Don't";            # Don't
my $name = 'John Doe';
say 'Hello $name';      # Hello $name
say "Hello $name";      # Hello John Doe
------------------------
